### ISSUE TITLE
not working correctly with wordpress 6 & btcpay v2 ... cheers 

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/woocommerce-greenfield-plugin#7]
**Describe the bug**

** Woocommerce System Status **

**WooCommerce Plugin Logs (if applicable)**

**Your BTCPay Environment (please complete the following information):**

- BTCPay Server Version:    
- Deployment Method:        
- Browser:                  

**Additional context**

**Screenshots / Video / GIf (if applicable)**

**Comment by Eskyee** [comment]
from error logs: 

2022-06-13T17:14:13+00:00 CRITICAL Uncaught Error: Class 'BTCPayServer\Util\PreciseNumber' not found in /var/www/html/wp-content/plugins/btcpay-greenfield-for-woocommerce/src/Gateway/AbstractGateway.php:490
Stack trace:
#0 /var/www/html/wp-content/plugins/btcpay-greenfield-for-woocommerce/src/Gateway/AbstractGateway.php(109): BTCPayServer\WC\Gateway\AbstractGateway->createInvoice(Object(WC_Order))
#1 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(982): BTCPayServer\WC\Gateway\AbstractGateway->process_payment(119)
#2 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1206): WC_Checkout->process_order_payment(119, 'btcpaygf_defaul...')
#3 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(461): WC_Checkout->process_checkout()
#4 /var/www/html/wp-includes/class-wp-hook.php(307): WC_AJAX::checkout('')
#5 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#6 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#7 /var/www/html in /var/www/html/wp-content/plugins/btcpay-greenfield-for-woocommerce/src/Gateway/AbstractGateway.php on line 490
